### ISSUE TITLE
MISBUCKET: SIGABRT_libstdc++.so.6!__gnu_cxx::__verbose_terminate_handler

### ISSUE THREAD

**Issue by schaabs** [Microsoft/dotnet-reliability#44]
The entire module libstdc++.so.6 should be ignored.  It is in a common managed code failure path, plus we can assume that the c++ std library is clean for our stress bucketing.

	libc.so.6!gsignal
    libc.so.6!abort
    libstdc++.so.6!__gnu_cxx::__verbose_terminate_handler()
    libstdc++.so.6!???
    libstdc++.so.6!std::terminate()
    libstdc++.so.6!__cxa_allocate_exception
    libcoreclr.so!RtlpRaiseException(_EXCEPTION_RECORD*)
    libcoreclr.so!RaiseException
    libcoreclr.so!RaiseTheExceptionInternalOnly(Object*, int, int)
    libcoreclr.so!IL_Throw(Object*)
    ...

**Comment by lt72** [comment]
is the allocation of the exception a failure due to OOM?

**Comment by schaabs** [comment]
In this case yes, but there are a handful of failures which are getting bucketed here so we need to update the bucketing to properly blame the calling modules
